<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>//div[contains(@id,'MoreFilters')]/button</description>
   <name>btnMoreFilters</name>
   <tag></tag>
   <elementGuidId>67335363-1e7d-491d-ba3f-eee76de64463</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[contains(@id,'MoreFilters')]/button</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
